/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as SellerAtividadesRouteImport } from './routes/seller/atividades'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAtividadesRoute = SellerAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => SellerRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/dashboard'
    | '/seller/atividades'
    | '/seller/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/dashboard'
    | '/seller/atividades'
    | '/seller/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/dashboard'
    | '/seller/atividades'
    | '/seller/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SellerRoute: typeof SellerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/atividades': {
      id: '/seller/atividades'
      path: '/atividades'
      fullPath: '/seller/atividades'
      preLoaderRoute: typeof SellerAtividadesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerAtividadesRoute: typeof SellerAtividadesRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAtividadesRoute: SellerAtividadesRoute,
  SellerDashboardRoute: SellerDashboardRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
