/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerEmpresasRouteImport } from './routes/seller/empresas'
import { Route as SellerDashboardRouteImport } from './routes/seller/dashboard'
import { Route as SellerAtividadesRouteImport } from './routes/seller/atividades'
import { Route as SellerAgendaRouteImport } from './routes/seller/agenda'
import { Route as AdminVendedoresRouteImport } from './routes/admin/vendedores'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCidadesRouteImport } from './routes/admin/cidades'
import { Route as AdminAtividadesRouteImport } from './routes/admin/atividades'
import { Route as AdminAlertasRouteImport } from './routes/admin/alertas'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerEmpresasRoute = SellerEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => SellerRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAtividadesRoute = SellerAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => SellerRoute,
} as any)
const SellerAgendaRoute = SellerAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => SellerRoute,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtividadesRoute = AdminAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/seller/agenda': typeof SellerAgendaRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/empresas': typeof SellerEmpresasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/seller/agenda': typeof SellerAgendaRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/empresas': typeof SellerEmpresasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/atividades': typeof AdminAtividadesRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/seller/agenda': typeof SellerAgendaRoute
  '/seller/atividades': typeof SellerAtividadesRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/empresas': typeof SellerEmpresasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/alertas'
    | '/admin/atividades'
    | '/admin/cidades'
    | '/admin/dashboard'
    | '/admin/vendedores'
    | '/seller/agenda'
    | '/seller/atividades'
    | '/seller/dashboard'
    | '/seller/empresas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/alertas'
    | '/admin/atividades'
    | '/admin/cidades'
    | '/admin/dashboard'
    | '/admin/vendedores'
    | '/seller/agenda'
    | '/seller/atividades'
    | '/seller/dashboard'
    | '/seller/empresas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/seller'
    | '/admin/alertas'
    | '/admin/atividades'
    | '/admin/cidades'
    | '/admin/dashboard'
    | '/admin/vendedores'
    | '/seller/agenda'
    | '/seller/atividades'
    | '/seller/dashboard'
    | '/seller/empresas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SellerRoute: typeof SellerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/empresas': {
      id: '/seller/empresas'
      path: '/empresas'
      fullPath: '/seller/empresas'
      preLoaderRoute: typeof SellerEmpresasRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/atividades': {
      id: '/seller/atividades'
      path: '/atividades'
      fullPath: '/seller/atividades'
      preLoaderRoute: typeof SellerAtividadesRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/agenda': {
      id: '/seller/agenda'
      path: '/agenda'
      fullPath: '/seller/agenda'
      preLoaderRoute: typeof SellerAgendaRouteImport
      parentRoute: typeof SellerRoute
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atividades': {
      id: '/admin/atividades'
      path: '/atividades'
      fullPath: '/admin/atividades'
      preLoaderRoute: typeof AdminAtividadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminAtividadesRoute: typeof AdminAtividadesRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminAtividadesRoute: AdminAtividadesRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SellerRouteChildren {
  SellerAgendaRoute: typeof SellerAgendaRoute
  SellerAtividadesRoute: typeof SellerAtividadesRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerEmpresasRoute: typeof SellerEmpresasRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerAgendaRoute: SellerAgendaRoute,
  SellerAtividadesRoute: SellerAtividadesRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerEmpresasRoute: SellerEmpresasRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
